version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "anindya"
    assignees:
      - "anindya"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    versioning-strategy: "increase"
    
    # Group minor and patch updates
    groups:
      production-dependencies:
        patterns:
          - "@commander-js/extra-typings"
          - "chalk"
          - "cheerio"
          - "got"
          - "inquirer"
          - "update-notifier"
        update-types:
          - "minor"
          - "patch"
      
      development-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "prettier*"
        update-types:
          - "minor"
          - "patch"
    
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "anindya"
    assignees:
      - "anindya"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "oven-sh/*"
          - "codecov/*"
        update-types:
          - "minor"
          - "patch"